apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: zoo-httpanimal
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 1
    useBuildkit: false
    useDockerCLI: false
  artifacts:
  - image: http-animal
    context: .
    # sync:
    #   manual:
    #   - src: "src/*.py"
    #     dest: "/app"
    #     strip: "src"
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/deployment-dev.yaml