---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-animal-dev
  labels:
    app: http-animal-dev
    version: v1
    group: zoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-animal-dev
      version: v1
      group: zoo
  template:
    metadata:
      labels:
        app: http-animal-dev
        version: v1
        group: zoo
    spec:
      containers:
      - name: animal
        image: http-animal
        ports:
        - containerPort: 5000
        env:
          - name: ACTIONS
            value: "roars!,looks in your general direction.,walks back and forth glaring at you."
          - name: NAME
            value: "tiger"
---
apiVersion: v1
kind: Service
metadata:
  name: http-animal-dev
spec:
  selector:
    app: http-animal-dev
    group: zoo
    version: v1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http